### ISSUE TITLE
I just want to know how to use this?

### ISSUE THREAD

**Issue by soliury** [syscoin/blockmarket#3]
Do I need to run the syscoin wallet ?

**Comment by dwasyluk** [comment]
Yes, sorry this is still in development but we will have full documentation when it's ready for production release.

For blockmarket to work you must be running the 0.1.6 wallet which is still in development. You can grab the code for it from https://github.com/syscoin/syscoin/tree/devstaging-0.1.6-v2wallet. Build using that branch to get things up and running. The daemon must be running in order for blockmarket to operate.

More thorough documentation will be provided after the production release.
